# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataBaseGUIdesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DataBaseGUI(object):
    def setupUi(self, DataBaseGUI):
        DataBaseGUI.setObjectName(_fromUtf8("DataBaseGUI"))
        DataBaseGUI.resize(2222, 1523)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DataBaseGUI.sizePolicy().hasHeightForWidth())
        DataBaseGUI.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(DataBaseGUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.RefreshPlot1PushButton = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RefreshPlot1PushButton.sizePolicy().hasHeightForWidth())
        self.RefreshPlot1PushButton.setSizePolicy(sizePolicy)
        self.RefreshPlot1PushButton.setObjectName(_fromUtf8("RefreshPlot1PushButton"))
        self.verticalLayout_8.addWidget(self.RefreshPlot1PushButton)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.EndDateEdit = QtGui.QDateEdit(self.tab_4)
        self.EndDateEdit.setDate(QtCore.QDate(2017, 12, 31))
        self.EndDateEdit.setObjectName(_fromUtf8("EndDateEdit"))
        self.gridLayout_18.addWidget(self.EndDateEdit, 0, 3, 1, 1)
        self.StartDateEdit = QtGui.QDateEdit(self.tab_4)
        self.StartDateEdit.setDate(QtCore.QDate(2017, 1, 1))
        self.StartDateEdit.setObjectName(_fromUtf8("StartDateEdit"))
        self.gridLayout_18.addWidget(self.StartDateEdit, 0, 1, 1, 1)
        self.StartDateLabel_7 = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartDateLabel_7.sizePolicy().hasHeightForWidth())
        self.StartDateLabel_7.setSizePolicy(sizePolicy)
        self.StartDateLabel_7.setObjectName(_fromUtf8("StartDateLabel_7"))
        self.gridLayout_18.addWidget(self.StartDateLabel_7, 0, 2, 1, 1)
        self.StartDateLabel_8 = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartDateLabel_8.sizePolicy().hasHeightForWidth())
        self.StartDateLabel_8.setSizePolicy(sizePolicy)
        self.StartDateLabel_8.setObjectName(_fromUtf8("StartDateLabel_8"))
        self.gridLayout_18.addWidget(self.StartDateLabel_8, 0, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_18)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.GearLabel = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GearLabel.sizePolicy().hasHeightForWidth())
        self.GearLabel.setSizePolicy(sizePolicy)
        self.GearLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GearLabel.setObjectName(_fromUtf8("GearLabel"))
        self.gridLayout_3.addWidget(self.GearLabel, 0, 3, 1, 1)
        self.ActivitiesListWidget = QtGui.QListWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ActivitiesListWidget.sizePolicy().hasHeightForWidth())
        self.ActivitiesListWidget.setSizePolicy(sizePolicy)
        self.ActivitiesListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ActivitiesListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.ActivitiesListWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.ActivitiesListWidget.setObjectName(_fromUtf8("ActivitiesListWidget"))
        self.gridLayout_3.addWidget(self.ActivitiesListWidget, 1, 2, 1, 1)
        self.SportsListWidget = QtGui.QListWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SportsListWidget.sizePolicy().hasHeightForWidth())
        self.SportsListWidget.setSizePolicy(sizePolicy)
        self.SportsListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SportsListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.SportsListWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.SportsListWidget.setObjectName(_fromUtf8("SportsListWidget"))
        self.gridLayout_3.addWidget(self.SportsListWidget, 1, 0, 1, 1)
        self.GearListWidget = QtGui.QListWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GearListWidget.sizePolicy().hasHeightForWidth())
        self.GearListWidget.setSizePolicy(sizePolicy)
        self.GearListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.GearListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.GearListWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.GearListWidget.setObjectName(_fromUtf8("GearListWidget"))
        self.gridLayout_3.addWidget(self.GearListWidget, 1, 3, 1, 1)
        self.SportsLabel = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SportsLabel.sizePolicy().hasHeightForWidth())
        self.SportsLabel.setSizePolicy(sizePolicy)
        self.SportsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SportsLabel.setObjectName(_fromUtf8("SportsLabel"))
        self.gridLayout_3.addWidget(self.SportsLabel, 0, 0, 1, 1)
        self.ActivitiesLabel = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ActivitiesLabel.sizePolicy().hasHeightForWidth())
        self.ActivitiesLabel.setSizePolicy(sizePolicy)
        self.ActivitiesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ActivitiesLabel.setObjectName(_fromUtf8("ActivitiesLabel"))
        self.gridLayout_3.addWidget(self.ActivitiesLabel, 0, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_3)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.EndLocationLabel = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndLocationLabel.sizePolicy().hasHeightForWidth())
        self.EndLocationLabel.setSizePolicy(sizePolicy)
        self.EndLocationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EndLocationLabel.setObjectName(_fromUtf8("EndLocationLabel"))
        self.gridLayout_7.addWidget(self.EndLocationLabel, 2, 2, 1, 1)
        self.EndLocationListWidget = QtGui.QListWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndLocationListWidget.sizePolicy().hasHeightForWidth())
        self.EndLocationListWidget.setSizePolicy(sizePolicy)
        self.EndLocationListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.EndLocationListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.EndLocationListWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.EndLocationListWidget.setObjectName(_fromUtf8("EndLocationListWidget"))
        self.gridLayout_7.addWidget(self.EndLocationListWidget, 3, 2, 1, 1)
        self.StartLocationLabel = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartLocationLabel.sizePolicy().hasHeightForWidth())
        self.StartLocationLabel.setSizePolicy(sizePolicy)
        self.StartLocationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StartLocationLabel.setObjectName(_fromUtf8("StartLocationLabel"))
        self.gridLayout_7.addWidget(self.StartLocationLabel, 2, 0, 1, 1)
        self.StartLocationListWidget = QtGui.QListWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartLocationListWidget.sizePolicy().hasHeightForWidth())
        self.StartLocationListWidget.setSizePolicy(sizePolicy)
        self.StartLocationListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.StartLocationListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.StartLocationListWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.StartLocationListWidget.setObjectName(_fromUtf8("StartLocationListWidget"))
        self.gridLayout_7.addWidget(self.StartLocationListWidget, 3, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.ReadFilePathWidget = QtGui.QLineEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ReadFilePathWidget.setFont(font)
        self.ReadFilePathWidget.setObjectName(_fromUtf8("ReadFilePathWidget"))
        self.gridLayout_9.addWidget(self.ReadFilePathWidget, 0, 1, 1, 1)
        self.NewFilePushButton = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewFilePushButton.sizePolicy().hasHeightForWidth())
        self.NewFilePushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.NewFilePushButton.setFont(font)
        self.NewFilePushButton.setObjectName(_fromUtf8("NewFilePushButton"))
        self.gridLayout_9.addWidget(self.NewFilePushButton, 0, 0, 1, 1)
        self.SaveFilePathWidget = QtGui.QLineEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SaveFilePathWidget.setFont(font)
        self.SaveFilePathWidget.setObjectName(_fromUtf8("SaveFilePathWidget"))
        self.gridLayout_9.addWidget(self.SaveFilePathWidget, 1, 1, 1, 1)
        self.SaveDataPushButton = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveDataPushButton.sizePolicy().hasHeightForWidth())
        self.SaveDataPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SaveDataPushButton.setFont(font)
        self.SaveDataPushButton.setObjectName(_fromUtf8("SaveDataPushButton"))
        self.gridLayout_9.addWidget(self.SaveDataPushButton, 1, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_9)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.Label_10 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_10.sizePolicy().hasHeightForWidth())
        self.Label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_10.setFont(font)
        self.Label_10.setObjectName(_fromUtf8("Label_10"))
        self.gridLayout_14.addWidget(self.Label_10, 1, 0, 1, 1)
        self.Label_9 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_9.sizePolicy().hasHeightForWidth())
        self.Label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_9.setFont(font)
        self.Label_9.setObjectName(_fromUtf8("Label_9"))
        self.gridLayout_14.addWidget(self.Label_9, 0, 0, 1, 1)
        self.DatabaseRowsSpinBox = QtGui.QSpinBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DatabaseRowsSpinBox.setFont(font)
        self.DatabaseRowsSpinBox.setMaximum(100000)
        self.DatabaseRowsSpinBox.setProperty("value", 50)
        self.DatabaseRowsSpinBox.setObjectName(_fromUtf8("DatabaseRowsSpinBox"))
        self.gridLayout_14.addWidget(self.DatabaseRowsSpinBox, 1, 1, 1, 1)
        self.DatabaseSizeSpinBox = QtGui.QSpinBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DatabaseSizeSpinBox.setFont(font)
        self.DatabaseSizeSpinBox.setReadOnly(True)
        self.DatabaseSizeSpinBox.setMaximum(100000)
        self.DatabaseSizeSpinBox.setProperty("value", 50)
        self.DatabaseSizeSpinBox.setObjectName(_fromUtf8("DatabaseSizeSpinBox"))
        self.gridLayout_14.addWidget(self.DatabaseSizeSpinBox, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_14)
        self.Table1Widget = QtGui.QTableWidget(self.tab_3)
        self.Table1Widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.Table1Widget.setObjectName(_fromUtf8("Table1Widget"))
        self.Table1Widget.setColumnCount(0)
        self.Table1Widget.setRowCount(0)
        self.Table1Widget.horizontalHeader().setSortIndicatorShown(False)
        self.Table1Widget.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_7.addWidget(self.Table1Widget)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tabWidget1 = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget1.sizePolicy().hasHeightForWidth())
        self.tabWidget1.setSizePolicy(sizePolicy)
        self.tabWidget1.setMinimumSize(QtCore.QSize(1100, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget1.setFont(font)
        self.tabWidget1.setObjectName(_fromUtf8("tabWidget1"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_23 = QtGui.QGridLayout()
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.MapCheckBox = QtGui.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.MapCheckBox.setFont(font)
        self.MapCheckBox.setObjectName(_fromUtf8("MapCheckBox"))
        self.gridLayout_23.addWidget(self.MapCheckBox, 0, 1, 1, 1)
        self.PlotMapPushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlotMapPushButton.sizePolicy().hasHeightForWidth())
        self.PlotMapPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PlotMapPushButton.setFont(font)
        self.PlotMapPushButton.setObjectName(_fromUtf8("PlotMapPushButton"))
        self.gridLayout_23.addWidget(self.PlotMapPushButton, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_23)
        self.gridLayout_38 = QtGui.QGridLayout()
        self.gridLayout_38.setObjectName(_fromUtf8("gridLayout_38"))
        self.Label_11 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_11.sizePolicy().hasHeightForWidth())
        self.Label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_11.setFont(font)
        self.Label_11.setObjectName(_fromUtf8("Label_11"))
        self.gridLayout_38.addWidget(self.Label_11, 0, 0, 1, 1)
        self.MapActivitiesSpinBox = QtGui.QSpinBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.MapActivitiesSpinBox.setFont(font)
        self.MapActivitiesSpinBox.setMaximum(100000)
        self.MapActivitiesSpinBox.setProperty("value", 5)
        self.MapActivitiesSpinBox.setObjectName(_fromUtf8("MapActivitiesSpinBox"))
        self.gridLayout_38.addWidget(self.MapActivitiesSpinBox, 0, 1, 1, 1)
        self.LegendLabel_17 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LegendLabel_17.sizePolicy().hasHeightForWidth())
        self.LegendLabel_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LegendLabel_17.setFont(font)
        self.LegendLabel_17.setObjectName(_fromUtf8("LegendLabel_17"))
        self.gridLayout_38.addWidget(self.LegendLabel_17, 0, 2, 1, 1)
        self.MapLegendComboBox = QtGui.QComboBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MapLegendComboBox.sizePolicy().hasHeightForWidth())
        self.MapLegendComboBox.setSizePolicy(sizePolicy)
        self.MapLegendComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.MapLegendComboBox.setDuplicatesEnabled(False)
        self.MapLegendComboBox.setObjectName(_fromUtf8("MapLegendComboBox"))
        self.gridLayout_38.addWidget(self.MapLegendComboBox, 0, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_38)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.SaveMapPushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveMapPushButton.sizePolicy().hasHeightForWidth())
        self.SaveMapPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SaveMapPushButton.setFont(font)
        self.SaveMapPushButton.setObjectName(_fromUtf8("SaveMapPushButton"))
        self.gridLayout.addWidget(self.SaveMapPushButton, 0, 1, 1, 1)
        self.MapFilePathWidget = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.MapFilePathWidget.setFont(font)
        self.MapFilePathWidget.setObjectName(_fromUtf8("MapFilePathWidget"))
        self.gridLayout.addWidget(self.MapFilePathWidget, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.MapWidgetContainer = QtGui.QVBoxLayout()
        self.MapWidgetContainer.setObjectName(_fromUtf8("MapWidgetContainer"))
        self.verticalLayout_6.addLayout(self.MapWidgetContainer)
        self.tabWidget1.addTab(self.tab_2, _fromUtf8(""))
        self.Tab1 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab1.sizePolicy().hasHeightForWidth())
        self.Tab1.setSizePolicy(sizePolicy)
        self.Tab1.setObjectName(_fromUtf8("Tab1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Tab1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ScatterXComboBox = QtGui.QComboBox(self.Tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScatterXComboBox.sizePolicy().hasHeightForWidth())
        self.ScatterXComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ScatterXComboBox.setFont(font)
        self.ScatterXComboBox.setObjectName(_fromUtf8("ScatterXComboBox"))
        self.gridLayout_2.addWidget(self.ScatterXComboBox, 0, 1, 1, 1)
        self.LegendLabel = QtGui.QLabel(self.Tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LegendLabel.sizePolicy().hasHeightForWidth())
        self.LegendLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LegendLabel.setFont(font)
        self.LegendLabel.setObjectName(_fromUtf8("LegendLabel"))
        self.gridLayout_2.addWidget(self.LegendLabel, 1, 2, 1, 1)
        self.ScatterLegendComboBox = QtGui.QComboBox(self.Tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScatterLegendComboBox.sizePolicy().hasHeightForWidth())
        self.ScatterLegendComboBox.setSizePolicy(sizePolicy)
        self.ScatterLegendComboBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ScatterLegendComboBox.setFont(font)
        self.ScatterLegendComboBox.setDuplicatesEnabled(False)
        self.ScatterLegendComboBox.setObjectName(_fromUtf8("ScatterLegendComboBox"))
        self.gridLayout_2.addWidget(self.ScatterLegendComboBox, 1, 3, 1, 1)
        self.XLabel1 = QtGui.QLabel(self.Tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XLabel1.sizePolicy().hasHeightForWidth())
        self.XLabel1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.XLabel1.setFont(font)
        self.XLabel1.setObjectName(_fromUtf8("XLabel1"))
        self.gridLayout_2.addWidget(self.XLabel1, 0, 0, 1, 1)
        self.SizeLabel = QtGui.QLabel(self.Tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SizeLabel.sizePolicy().hasHeightForWidth())
        self.SizeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SizeLabel.setFont(font)
        self.SizeLabel.setObjectName(_fromUtf8("SizeLabel"))
        self.gridLayout_2.addWidget(self.SizeLabel, 1, 0, 1, 1)
        self.ScatterSizeComboBox = QtGui.QComboBox(self.Tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScatterSizeComboBox.sizePolicy().hasHeightForWidth())
        self.ScatterSizeComboBox.setSizePolicy(sizePolicy)
        self.ScatterSizeComboBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ScatterSizeComboBox.setFont(font)
        self.ScatterSizeComboBox.setDuplicatesEnabled(False)
        self.ScatterSizeComboBox.setObjectName(_fromUtf8("ScatterSizeComboBox"))
        self.gridLayout_2.addWidget(self.ScatterSizeComboBox, 1, 1, 1, 1)
        self.ScatterYComboBox = QtGui.QComboBox(self.Tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScatterYComboBox.sizePolicy().hasHeightForWidth())
        self.ScatterYComboBox.setSizePolicy(sizePolicy)
        self.ScatterYComboBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ScatterYComboBox.setFont(font)
        self.ScatterYComboBox.setDuplicatesEnabled(False)
        self.ScatterYComboBox.setObjectName(_fromUtf8("ScatterYComboBox"))
        self.gridLayout_2.addWidget(self.ScatterYComboBox, 0, 3, 1, 1)
        self.YLabel1 = QtGui.QLabel(self.Tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YLabel1.sizePolicy().hasHeightForWidth())
        self.YLabel1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.YLabel1.setFont(font)
        self.YLabel1.setObjectName(_fromUtf8("YLabel1"))
        self.gridLayout_2.addWidget(self.YLabel1, 0, 2, 1, 1)
        self.LegendLabel_12 = QtGui.QLabel(self.Tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LegendLabel_12.sizePolicy().hasHeightForWidth())
        self.LegendLabel_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LegendLabel_12.setFont(font)
        self.LegendLabel_12.setObjectName(_fromUtf8("LegendLabel_12"))
        self.gridLayout_2.addWidget(self.LegendLabel_12, 2, 0, 1, 1)
        self.ScatterCMapComboBox = QtGui.QComboBox(self.Tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScatterCMapComboBox.sizePolicy().hasHeightForWidth())
        self.ScatterCMapComboBox.setSizePolicy(sizePolicy)
        self.ScatterCMapComboBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ScatterCMapComboBox.setFont(font)
        self.ScatterCMapComboBox.setDuplicatesEnabled(False)
        self.ScatterCMapComboBox.setObjectName(_fromUtf8("ScatterCMapComboBox"))
        self.gridLayout_2.addWidget(self.ScatterCMapComboBox, 2, 1, 1, 1)
        self.ScatterPushButton = QtGui.QPushButton(self.Tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScatterPushButton.sizePolicy().hasHeightForWidth())
        self.ScatterPushButton.setSizePolicy(sizePolicy)
        self.ScatterPushButton.setObjectName(_fromUtf8("ScatterPushButton"))
        self.gridLayout_2.addWidget(self.ScatterPushButton, 2, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.PlotScatterWidgetContainer = QtGui.QVBoxLayout()
        self.PlotScatterWidgetContainer.setObjectName(_fromUtf8("PlotScatterWidgetContainer"))
        self.verticalLayout_3.addLayout(self.PlotScatterWidgetContainer)
        self.tabWidget1.addTab(self.Tab1, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.XLabel1_5 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XLabel1_5.sizePolicy().hasHeightForWidth())
        self.XLabel1_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.XLabel1_5.setFont(font)
        self.XLabel1_5.setObjectName(_fromUtf8("XLabel1_5"))
        self.gridLayout_20.addWidget(self.XLabel1_5, 0, 0, 1, 1)
        self.LegendLabel_5 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LegendLabel_5.sizePolicy().hasHeightForWidth())
        self.LegendLabel_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LegendLabel_5.setFont(font)
        self.LegendLabel_5.setObjectName(_fromUtf8("LegendLabel_5"))
        self.gridLayout_20.addWidget(self.LegendLabel_5, 0, 2, 1, 1)
        self.HistLegendComboBox = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HistLegendComboBox.sizePolicy().hasHeightForWidth())
        self.HistLegendComboBox.setSizePolicy(sizePolicy)
        self.HistLegendComboBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.HistLegendComboBox.setFont(font)
        self.HistLegendComboBox.setDuplicatesEnabled(False)
        self.HistLegendComboBox.setObjectName(_fromUtf8("HistLegendComboBox"))
        self.gridLayout_20.addWidget(self.HistLegendComboBox, 0, 3, 1, 1)
        self.HistXComboBox = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HistXComboBox.sizePolicy().hasHeightForWidth())
        self.HistXComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.HistXComboBox.setFont(font)
        self.HistXComboBox.setObjectName(_fromUtf8("HistXComboBox"))
        self.gridLayout_20.addWidget(self.HistXComboBox, 0, 1, 1, 1)
        self.LegendLabel_7 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LegendLabel_7.sizePolicy().hasHeightForWidth())
        self.LegendLabel_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LegendLabel_7.setFont(font)
        self.LegendLabel_7.setObjectName(_fromUtf8("LegendLabel_7"))
        self.gridLayout_20.addWidget(self.LegendLabel_7, 1, 0, 1, 1)
        self.HistCMapComboBox = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HistCMapComboBox.sizePolicy().hasHeightForWidth())
        self.HistCMapComboBox.setSizePolicy(sizePolicy)
        self.HistCMapComboBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.HistCMapComboBox.setFont(font)
        self.HistCMapComboBox.setDuplicatesEnabled(False)
        self.HistCMapComboBox.setObjectName(_fromUtf8("HistCMapComboBox"))
        self.gridLayout_20.addWidget(self.HistCMapComboBox, 1, 1, 1, 1)
        self.HistogramPushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HistogramPushButton.sizePolicy().hasHeightForWidth())
        self.HistogramPushButton.setSizePolicy(sizePolicy)
        self.HistogramPushButton.setObjectName(_fromUtf8("HistogramPushButton"))
        self.gridLayout_20.addWidget(self.HistogramPushButton, 1, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_20)
        self.PlotHistWidgetContainer = QtGui.QVBoxLayout()
        self.PlotHistWidgetContainer.setObjectName(_fromUtf8("PlotHistWidgetContainer"))
        self.verticalLayout_5.addLayout(self.PlotHistWidgetContainer)
        self.tabWidget1.addTab(self.tab, _fromUtf8(""))
        self.Tab3 = QtGui.QWidget()
        self.Tab3.setObjectName(_fromUtf8("Tab3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Tab3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.StartTimeLabel_4 = QtGui.QLabel(self.Tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartTimeLabel_4.sizePolicy().hasHeightForWidth())
        self.StartTimeLabel_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StartTimeLabel_4.setFont(font)
        self.StartTimeLabel_4.setObjectName(_fromUtf8("StartTimeLabel_4"))
        self.verticalLayout_2.addWidget(self.StartTimeLabel_4)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.XComboBox2 = QtGui.QComboBox(self.Tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XComboBox2.sizePolicy().hasHeightForWidth())
        self.XComboBox2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.XComboBox2.setFont(font)
        self.XComboBox2.setObjectName(_fromUtf8("XComboBox2"))
        self.gridLayout_6.addWidget(self.XComboBox2, 0, 1, 1, 1)
        self.XLabel2 = QtGui.QLabel(self.Tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XLabel2.sizePolicy().hasHeightForWidth())
        self.XLabel2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.XLabel2.setFont(font)
        self.XLabel2.setObjectName(_fromUtf8("XLabel2"))
        self.gridLayout_6.addWidget(self.XLabel2, 0, 0, 1, 1)
        self.EndTimeLabel = QtGui.QLabel(self.Tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndTimeLabel.sizePolicy().hasHeightForWidth())
        self.EndTimeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.EndTimeLabel.setFont(font)
        self.EndTimeLabel.setObjectName(_fromUtf8("EndTimeLabel"))
        self.gridLayout_6.addWidget(self.EndTimeLabel, 1, 2, 1, 1)
        self.EndTimeDoubleSpinBox = QtGui.QDoubleSpinBox(self.Tab3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.EndTimeDoubleSpinBox.setFont(font)
        self.EndTimeDoubleSpinBox.setMaximum(10000000.0)
        self.EndTimeDoubleSpinBox.setSingleStep(0.05)
        self.EndTimeDoubleSpinBox.setProperty("value", 1000.0)
        self.EndTimeDoubleSpinBox.setObjectName(_fromUtf8("EndTimeDoubleSpinBox"))
        self.gridLayout_6.addWidget(self.EndTimeDoubleSpinBox, 1, 3, 1, 1)
        self.YLabel2 = QtGui.QLabel(self.Tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YLabel2.sizePolicy().hasHeightForWidth())
        self.YLabel2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.YLabel2.setFont(font)
        self.YLabel2.setObjectName(_fromUtf8("YLabel2"))
        self.gridLayout_6.addWidget(self.YLabel2, 0, 2, 1, 1)
        self.StartTimeLabel = QtGui.QLabel(self.Tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartTimeLabel.sizePolicy().hasHeightForWidth())
        self.StartTimeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StartTimeLabel.setFont(font)
        self.StartTimeLabel.setObjectName(_fromUtf8("StartTimeLabel"))
        self.gridLayout_6.addWidget(self.StartTimeLabel, 1, 0, 1, 1)
        self.YComboBox2 = QtGui.QComboBox(self.Tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YComboBox2.sizePolicy().hasHeightForWidth())
        self.YComboBox2.setSizePolicy(sizePolicy)
        self.YComboBox2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.YComboBox2.setFont(font)
        self.YComboBox2.setDuplicatesEnabled(False)
        self.YComboBox2.setObjectName(_fromUtf8("YComboBox2"))
        self.gridLayout_6.addWidget(self.YComboBox2, 0, 3, 1, 1)
        self.StartTimeDoubleSpinBox = QtGui.QDoubleSpinBox(self.Tab3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StartTimeDoubleSpinBox.setFont(font)
        self.StartTimeDoubleSpinBox.setMaximum(10000000.0)
        self.StartTimeDoubleSpinBox.setSingleStep(0.05)
        self.StartTimeDoubleSpinBox.setObjectName(_fromUtf8("StartTimeDoubleSpinBox"))
        self.gridLayout_6.addWidget(self.StartTimeDoubleSpinBox, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.RefreshPlot2PushButton = QtGui.QPushButton(self.Tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RefreshPlot2PushButton.sizePolicy().hasHeightForWidth())
        self.RefreshPlot2PushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RefreshPlot2PushButton.setFont(font)
        self.RefreshPlot2PushButton.setObjectName(_fromUtf8("RefreshPlot2PushButton"))
        self.verticalLayout_2.addWidget(self.RefreshPlot2PushButton)
        self.Plot2WidgetContainer = QtGui.QVBoxLayout()
        self.Plot2WidgetContainer.setObjectName(_fromUtf8("Plot2WidgetContainer"))
        self.verticalLayout_2.addLayout(self.Plot2WidgetContainer)
        self.tabWidget1.addTab(self.Tab3, _fromUtf8(""))
        self.Tab4 = QtGui.QWidget()
        self.Tab4.setObjectName(_fromUtf8("Tab4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Tab4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.WarningLabel2 = QtGui.QLabel(self.Tab4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WarningLabel2.sizePolicy().hasHeightForWidth())
        self.WarningLabel2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.WarningLabel2.setFont(font)
        self.WarningLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.WarningLabel2.setObjectName(_fromUtf8("WarningLabel2"))
        self.verticalLayout_4.addWidget(self.WarningLabel2)
        self.Table2Widget = QtGui.QTableWidget(self.Tab4)
        self.Table2Widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.Table2Widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.Table2Widget.setObjectName(_fromUtf8("Table2Widget"))
        self.Table2Widget.setColumnCount(0)
        self.Table2Widget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.Table2Widget)
        self.tabWidget1.addTab(self.Tab4, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.splitter)
        DataBaseGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(DataBaseGUI)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget1.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DataBaseGUI)

    def retranslateUi(self, DataBaseGUI):
        DataBaseGUI.setWindowTitle(_translate("DataBaseGUI", "Ana\'s GPS DataBase", None))
        self.RefreshPlot1PushButton.setText(_translate("DataBaseGUI", "Filter database", None))
        self.StartDateLabel_7.setText(_translate("DataBaseGUI", "End date: ", None))
        self.StartDateLabel_8.setText(_translate("DataBaseGUI", "Start date: ", None))
        self.GearLabel.setText(_translate("DataBaseGUI", "Gear:", None))
        self.SportsLabel.setText(_translate("DataBaseGUI", "Sports:", None))
        self.ActivitiesLabel.setText(_translate("DataBaseGUI", "Activities:", None))
        self.EndLocationLabel.setText(_translate("DataBaseGUI", "End Location:", None))
        self.StartLocationLabel.setText(_translate("DataBaseGUI", "Start Location:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("DataBaseGUI", "Filters", None))
        self.NewFilePushButton.setText(_translate("DataBaseGUI", " Select New Database File: ", None))
        self.SaveDataPushButton.setText(_translate("DataBaseGUI", " Save Database to File: ", None))
        self.Label_10.setText(_translate("DataBaseGUI", "Number of rows to display: ", None))
        self.Label_9.setText(_translate("DataBaseGUI", "Number of rows in the filtered database: ", None))
        self.Table1Widget.setSortingEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DataBaseGUI", "Database", None))
        self.MapCheckBox.setText(_translate("DataBaseGUI", "Generate map when filtering. ", None))
        self.PlotMapPushButton.setText(_translate("DataBaseGUI", "Update map (it can be very slow). ", None))
        self.Label_11.setText(_translate("DataBaseGUI", "Number of activities to display: ", None))
        self.LegendLabel_17.setText(_translate("DataBaseGUI", "Legend: ", None))
        self.SaveMapPushButton.setText(_translate("DataBaseGUI", " Save Map to File: ", None))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tab_2), _translate("DataBaseGUI", "Map", None))
        self.LegendLabel.setText(_translate("DataBaseGUI", "Legend: ", None))
        self.XLabel1.setText(_translate("DataBaseGUI", "X Axis: ", None))
        self.SizeLabel.setText(_translate("DataBaseGUI", "Marker Size: ", None))
        self.YLabel1.setText(_translate("DataBaseGUI", "Y Axis: ", None))
        self.LegendLabel_12.setText(_translate("DataBaseGUI", "Color Map: ", None))
        self.ScatterPushButton.setText(_translate("DataBaseGUI", "Update scatter plot", None))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.Tab1), _translate("DataBaseGUI", "Scatter", None))
        self.XLabel1_5.setText(_translate("DataBaseGUI", "X Axis: ", None))
        self.LegendLabel_5.setText(_translate("DataBaseGUI", "Legend: ", None))
        self.LegendLabel_7.setText(_translate("DataBaseGUI", "Color Map: ", None))
        self.HistogramPushButton.setText(_translate("DataBaseGUI", "Update histogram plot", None))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tab), _translate("DataBaseGUI", "Histogram", None))
        self.StartTimeLabel_4.setText(_translate("DataBaseGUI", "Select rows from the database table and plot their data below.", None))
        self.XLabel2.setText(_translate("DataBaseGUI", "X Axis: ", None))
        self.EndTimeLabel.setText(_translate("DataBaseGUI", "End time (min): ", None))
        self.YLabel2.setText(_translate("DataBaseGUI", "Y Axis: ", None))
        self.StartTimeLabel.setText(_translate("DataBaseGUI", "Start time (min): ", None))
        self.RefreshPlot2PushButton.setText(_translate("DataBaseGUI", "Read activities and update database", None))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.Tab3), _translate("DataBaseGUI", "Trace", None))
        self.WarningLabel2.setText(_translate("DataBaseGUI", "Displays 50 rows maximum.", None))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.Tab4), _translate("DataBaseGUI", "Table", None))

