# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataBaseGUIdesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DataBaseGUI(object):
    def setupUi(self, DataBaseGUI):
        DataBaseGUI.setObjectName(_fromUtf8("DataBaseGUI"))
        DataBaseGUI.resize(2225, 1523)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DataBaseGUI.sizePolicy().hasHeightForWidth())
        DataBaseGUI.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(DataBaseGUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.ControlsPanel = QtGui.QVBoxLayout(self.layoutWidget)
        self.ControlsPanel.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.ControlsPanel.setObjectName(_fromUtf8("ControlsPanel"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ReadFilePathWidget = QtGui.QLineEdit(self.layoutWidget)
        self.ReadFilePathWidget.setObjectName(_fromUtf8("ReadFilePathWidget"))
        self.gridLayout.addWidget(self.ReadFilePathWidget, 0, 1, 1, 1)
        self.NewFilePushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewFilePushButton.sizePolicy().hasHeightForWidth())
        self.NewFilePushButton.setSizePolicy(sizePolicy)
        self.NewFilePushButton.setObjectName(_fromUtf8("NewFilePushButton"))
        self.gridLayout.addWidget(self.NewFilePushButton, 0, 0, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.SportsLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SportsLabel.sizePolicy().hasHeightForWidth())
        self.SportsLabel.setSizePolicy(sizePolicy)
        self.SportsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SportsLabel.setObjectName(_fromUtf8("SportsLabel"))
        self.gridLayout_3.addWidget(self.SportsLabel, 0, 0, 1, 1)
        self.ActivitiesLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ActivitiesLabel.sizePolicy().hasHeightForWidth())
        self.ActivitiesLabel.setSizePolicy(sizePolicy)
        self.ActivitiesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ActivitiesLabel.setObjectName(_fromUtf8("ActivitiesLabel"))
        self.gridLayout_3.addWidget(self.ActivitiesLabel, 0, 2, 1, 1)
        self.SportsListWidget = QtGui.QListWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SportsListWidget.sizePolicy().hasHeightForWidth())
        self.SportsListWidget.setSizePolicy(sizePolicy)
        self.SportsListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SportsListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.SportsListWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.SportsListWidget.setObjectName(_fromUtf8("SportsListWidget"))
        self.gridLayout_3.addWidget(self.SportsListWidget, 1, 0, 1, 1)
        self.ActivitiesListWidget = QtGui.QListWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ActivitiesListWidget.sizePolicy().hasHeightForWidth())
        self.ActivitiesListWidget.setSizePolicy(sizePolicy)
        self.ActivitiesListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ActivitiesListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.ActivitiesListWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.ActivitiesListWidget.setObjectName(_fromUtf8("ActivitiesListWidget"))
        self.gridLayout_3.addWidget(self.ActivitiesListWidget, 1, 2, 1, 1)
        self.GearLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GearLabel.sizePolicy().hasHeightForWidth())
        self.GearLabel.setSizePolicy(sizePolicy)
        self.GearLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GearLabel.setObjectName(_fromUtf8("GearLabel"))
        self.gridLayout_3.addWidget(self.GearLabel, 0, 3, 1, 1)
        self.GearListWidget = QtGui.QListWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GearListWidget.sizePolicy().hasHeightForWidth())
        self.GearListWidget.setSizePolicy(sizePolicy)
        self.GearListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.GearListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.GearListWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.GearListWidget.setObjectName(_fromUtf8("GearListWidget"))
        self.gridLayout_3.addWidget(self.GearListWidget, 1, 3, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_3)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.EndLocationLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndLocationLabel.sizePolicy().hasHeightForWidth())
        self.EndLocationLabel.setSizePolicy(sizePolicy)
        self.EndLocationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EndLocationLabel.setObjectName(_fromUtf8("EndLocationLabel"))
        self.gridLayout_7.addWidget(self.EndLocationLabel, 0, 2, 1, 1)
        self.StartLocationListWidget = QtGui.QListWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartLocationListWidget.sizePolicy().hasHeightForWidth())
        self.StartLocationListWidget.setSizePolicy(sizePolicy)
        self.StartLocationListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.StartLocationListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.StartLocationListWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.StartLocationListWidget.setObjectName(_fromUtf8("StartLocationListWidget"))
        self.gridLayout_7.addWidget(self.StartLocationListWidget, 2, 0, 1, 1)
        self.EndLocationListWidget = QtGui.QListWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndLocationListWidget.sizePolicy().hasHeightForWidth())
        self.EndLocationListWidget.setSizePolicy(sizePolicy)
        self.EndLocationListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.EndLocationListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.EndLocationListWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.EndLocationListWidget.setObjectName(_fromUtf8("EndLocationListWidget"))
        self.gridLayout_7.addWidget(self.EndLocationListWidget, 2, 2, 1, 1)
        self.StartLocationLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartLocationLabel.sizePolicy().hasHeightForWidth())
        self.StartLocationLabel.setSizePolicy(sizePolicy)
        self.StartLocationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StartLocationLabel.setObjectName(_fromUtf8("StartLocationLabel"))
        self.gridLayout_7.addWidget(self.StartLocationLabel, 0, 0, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_7)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.ControlsPanel.addWidget(self.line)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.XLabel1 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XLabel1.sizePolicy().hasHeightForWidth())
        self.XLabel1.setSizePolicy(sizePolicy)
        self.XLabel1.setObjectName(_fromUtf8("XLabel1"))
        self.gridLayout_2.addWidget(self.XLabel1, 4, 0, 1, 1)
        self.StartDateLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartDateLabel.sizePolicy().hasHeightForWidth())
        self.StartDateLabel.setSizePolicy(sizePolicy)
        self.StartDateLabel.setObjectName(_fromUtf8("StartDateLabel"))
        self.gridLayout_2.addWidget(self.StartDateLabel, 2, 0, 1, 1)
        self.XComboBox1 = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XComboBox1.sizePolicy().hasHeightForWidth())
        self.XComboBox1.setSizePolicy(sizePolicy)
        self.XComboBox1.setObjectName(_fromUtf8("XComboBox1"))
        self.gridLayout_2.addWidget(self.XComboBox1, 4, 2, 1, 1)
        self.YComboBox1 = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YComboBox1.sizePolicy().hasHeightForWidth())
        self.YComboBox1.setSizePolicy(sizePolicy)
        self.YComboBox1.setMinimumSize(QtCore.QSize(0, 0))
        self.YComboBox1.setDuplicatesEnabled(False)
        self.YComboBox1.setObjectName(_fromUtf8("YComboBox1"))
        self.gridLayout_2.addWidget(self.YComboBox1, 5, 2, 1, 1)
        self.StartDateEdit = QtGui.QDateEdit(self.layoutWidget)
        self.StartDateEdit.setDate(QtCore.QDate(2017, 1, 1))
        self.StartDateEdit.setObjectName(_fromUtf8("StartDateEdit"))
        self.gridLayout_2.addWidget(self.StartDateEdit, 2, 2, 1, 1)
        self.YLabel1 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YLabel1.sizePolicy().hasHeightForWidth())
        self.YLabel1.setSizePolicy(sizePolicy)
        self.YLabel1.setObjectName(_fromUtf8("YLabel1"))
        self.gridLayout_2.addWidget(self.YLabel1, 5, 0, 1, 1)
        self.StartDateLabel_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartDateLabel_2.sizePolicy().hasHeightForWidth())
        self.StartDateLabel_2.setSizePolicy(sizePolicy)
        self.StartDateLabel_2.setObjectName(_fromUtf8("StartDateLabel_2"))
        self.gridLayout_2.addWidget(self.StartDateLabel_2, 2, 3, 1, 1)
        self.EndDateEdit = QtGui.QDateEdit(self.layoutWidget)
        self.EndDateEdit.setDate(QtCore.QDate(2017, 12, 31))
        self.EndDateEdit.setObjectName(_fromUtf8("EndDateEdit"))
        self.gridLayout_2.addWidget(self.EndDateEdit, 2, 4, 1, 1)
        self.SizeLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SizeLabel.sizePolicy().hasHeightForWidth())
        self.SizeLabel.setSizePolicy(sizePolicy)
        self.SizeLabel.setObjectName(_fromUtf8("SizeLabel"))
        self.gridLayout_2.addWidget(self.SizeLabel, 4, 3, 1, 1)
        self.SizeComboBox = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SizeComboBox.sizePolicy().hasHeightForWidth())
        self.SizeComboBox.setSizePolicy(sizePolicy)
        self.SizeComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.SizeComboBox.setDuplicatesEnabled(False)
        self.SizeComboBox.setObjectName(_fromUtf8("SizeComboBox"))
        self.gridLayout_2.addWidget(self.SizeComboBox, 4, 4, 1, 1)
        self.LegendLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LegendLabel.sizePolicy().hasHeightForWidth())
        self.LegendLabel.setSizePolicy(sizePolicy)
        self.LegendLabel.setObjectName(_fromUtf8("LegendLabel"))
        self.gridLayout_2.addWidget(self.LegendLabel, 5, 3, 1, 1)
        self.LegendComboBox = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LegendComboBox.sizePolicy().hasHeightForWidth())
        self.LegendComboBox.setSizePolicy(sizePolicy)
        self.LegendComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.LegendComboBox.setDuplicatesEnabled(False)
        self.LegendComboBox.setObjectName(_fromUtf8("LegendComboBox"))
        self.gridLayout_2.addWidget(self.LegendComboBox, 5, 4, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_2)
        self.RefreshPlot1PushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RefreshPlot1PushButton.sizePolicy().hasHeightForWidth())
        self.RefreshPlot1PushButton.setSizePolicy(sizePolicy)
        self.RefreshPlot1PushButton.setObjectName(_fromUtf8("RefreshPlot1PushButton"))
        self.ControlsPanel.addWidget(self.RefreshPlot1PushButton)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.MapFilePathWidget = QtGui.QLineEdit(self.layoutWidget)
        self.MapFilePathWidget.setObjectName(_fromUtf8("MapFilePathWidget"))
        self.gridLayout_8.addWidget(self.MapFilePathWidget, 0, 1, 1, 1)
        self.SaveMapPushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveMapPushButton.sizePolicy().hasHeightForWidth())
        self.SaveMapPushButton.setSizePolicy(sizePolicy)
        self.SaveMapPushButton.setObjectName(_fromUtf8("SaveMapPushButton"))
        self.gridLayout_8.addWidget(self.SaveMapPushButton, 0, 0, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_8)
        self.line_4 = QtGui.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.ControlsPanel.addWidget(self.line_4)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.EndTimeLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndTimeLabel.sizePolicy().hasHeightForWidth())
        self.EndTimeLabel.setSizePolicy(sizePolicy)
        self.EndTimeLabel.setObjectName(_fromUtf8("EndTimeLabel"))
        self.gridLayout_6.addWidget(self.EndTimeLabel, 3, 3, 1, 1)
        self.StartTimeLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartTimeLabel.sizePolicy().hasHeightForWidth())
        self.StartTimeLabel.setSizePolicy(sizePolicy)
        self.StartTimeLabel.setObjectName(_fromUtf8("StartTimeLabel"))
        self.gridLayout_6.addWidget(self.StartTimeLabel, 2, 3, 1, 1)
        self.YLabel2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YLabel2.sizePolicy().hasHeightForWidth())
        self.YLabel2.setSizePolicy(sizePolicy)
        self.YLabel2.setObjectName(_fromUtf8("YLabel2"))
        self.gridLayout_6.addWidget(self.YLabel2, 3, 0, 1, 1)
        self.YComboBox2 = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YComboBox2.sizePolicy().hasHeightForWidth())
        self.YComboBox2.setSizePolicy(sizePolicy)
        self.YComboBox2.setMinimumSize(QtCore.QSize(0, 0))
        self.YComboBox2.setDuplicatesEnabled(False)
        self.YComboBox2.setObjectName(_fromUtf8("YComboBox2"))
        self.gridLayout_6.addWidget(self.YComboBox2, 3, 2, 1, 1)
        self.XComboBox2 = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XComboBox2.sizePolicy().hasHeightForWidth())
        self.XComboBox2.setSizePolicy(sizePolicy)
        self.XComboBox2.setObjectName(_fromUtf8("XComboBox2"))
        self.gridLayout_6.addWidget(self.XComboBox2, 2, 2, 1, 1)
        self.XLabel2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XLabel2.sizePolicy().hasHeightForWidth())
        self.XLabel2.setSizePolicy(sizePolicy)
        self.XLabel2.setObjectName(_fromUtf8("XLabel2"))
        self.gridLayout_6.addWidget(self.XLabel2, 2, 0, 1, 1)
        self.StartTimeDoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.StartTimeDoubleSpinBox.setMaximum(10000000.0)
        self.StartTimeDoubleSpinBox.setSingleStep(0.1)
        self.StartTimeDoubleSpinBox.setObjectName(_fromUtf8("StartTimeDoubleSpinBox"))
        self.gridLayout_6.addWidget(self.StartTimeDoubleSpinBox, 2, 4, 1, 1)
        self.EndTimeDoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.EndTimeDoubleSpinBox.setMaximum(10000000.0)
        self.EndTimeDoubleSpinBox.setSingleStep(0.1)
        self.EndTimeDoubleSpinBox.setProperty("value", 1000.0)
        self.EndTimeDoubleSpinBox.setObjectName(_fromUtf8("EndTimeDoubleSpinBox"))
        self.gridLayout_6.addWidget(self.EndTimeDoubleSpinBox, 3, 4, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_6)
        self.RefreshPlot2PushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RefreshPlot2PushButton.sizePolicy().hasHeightForWidth())
        self.RefreshPlot2PushButton.setSizePolicy(sizePolicy)
        self.RefreshPlot2PushButton.setObjectName(_fromUtf8("RefreshPlot2PushButton"))
        self.ControlsPanel.addWidget(self.RefreshPlot2PushButton)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.SaveFilePathWidget = QtGui.QLineEdit(self.layoutWidget)
        self.SaveFilePathWidget.setObjectName(_fromUtf8("SaveFilePathWidget"))
        self.gridLayout_5.addWidget(self.SaveFilePathWidget, 0, 1, 1, 1)
        self.SaveDataPushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveDataPushButton.sizePolicy().hasHeightForWidth())
        self.SaveDataPushButton.setSizePolicy(sizePolicy)
        self.SaveDataPushButton.setObjectName(_fromUtf8("SaveDataPushButton"))
        self.gridLayout_5.addWidget(self.SaveDataPushButton, 0, 0, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_5)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Tab1 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab1.sizePolicy().hasHeightForWidth())
        self.Tab1.setSizePolicy(sizePolicy)
        self.Tab1.setObjectName(_fromUtf8("Tab1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Tab1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.Plot1WidgetContainer = QtGui.QVBoxLayout()
        self.Plot1WidgetContainer.setObjectName(_fromUtf8("Plot1WidgetContainer"))
        self.verticalLayout_3.addLayout(self.Plot1WidgetContainer)
        self.tabWidget.addTab(self.Tab1, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.Plot3WidgetContainer = QtGui.QVBoxLayout()
        self.Plot3WidgetContainer.setObjectName(_fromUtf8("Plot3WidgetContainer"))
        self.verticalLayout_5.addLayout(self.Plot3WidgetContainer)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.Tab2 = QtGui.QWidget()
        self.Tab2.setObjectName(_fromUtf8("Tab2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Tab2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.WarningLabel1 = QtGui.QLabel(self.Tab2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WarningLabel1.sizePolicy().hasHeightForWidth())
        self.WarningLabel1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.WarningLabel1.setFont(font)
        self.WarningLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.WarningLabel1.setObjectName(_fromUtf8("WarningLabel1"))
        self.verticalLayout.addWidget(self.WarningLabel1)
        self.Table1Widget = QtGui.QTableWidget(self.Tab2)
        self.Table1Widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.Table1Widget.setObjectName(_fromUtf8("Table1Widget"))
        self.Table1Widget.setColumnCount(0)
        self.Table1Widget.setRowCount(0)
        self.verticalLayout.addWidget(self.Table1Widget)
        self.tabWidget.addTab(self.Tab2, _fromUtf8(""))
        self.Tab3 = QtGui.QWidget()
        self.Tab3.setObjectName(_fromUtf8("Tab3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Tab3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Plot2WidgetContainer = QtGui.QVBoxLayout()
        self.Plot2WidgetContainer.setObjectName(_fromUtf8("Plot2WidgetContainer"))
        self.verticalLayout_2.addLayout(self.Plot2WidgetContainer)
        self.tabWidget.addTab(self.Tab3, _fromUtf8(""))
        self.Tab4 = QtGui.QWidget()
        self.Tab4.setObjectName(_fromUtf8("Tab4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Tab4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.WarningLabel2 = QtGui.QLabel(self.Tab4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WarningLabel2.sizePolicy().hasHeightForWidth())
        self.WarningLabel2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.WarningLabel2.setFont(font)
        self.WarningLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.WarningLabel2.setObjectName(_fromUtf8("WarningLabel2"))
        self.verticalLayout_4.addWidget(self.WarningLabel2)
        self.Table2Widget = QtGui.QTableWidget(self.Tab4)
        self.Table2Widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.Table2Widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.Table2Widget.setObjectName(_fromUtf8("Table2Widget"))
        self.Table2Widget.setColumnCount(0)
        self.Table2Widget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.Table2Widget)
        self.tabWidget.addTab(self.Tab4, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.splitter)
        DataBaseGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(DataBaseGUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DataBaseGUI)

    def retranslateUi(self, DataBaseGUI):
        DataBaseGUI.setWindowTitle(_translate("DataBaseGUI", "Ana\'s GPS DataBase", None))
        self.NewFilePushButton.setText(_translate("DataBaseGUI", " Select New File: ", None))
        self.SportsLabel.setText(_translate("DataBaseGUI", "Sports:", None))
        self.ActivitiesLabel.setText(_translate("DataBaseGUI", "Activities:", None))
        self.GearLabel.setText(_translate("DataBaseGUI", "Gear:", None))
        self.EndLocationLabel.setText(_translate("DataBaseGUI", "End Location:", None))
        self.StartLocationLabel.setText(_translate("DataBaseGUI", "Start Location:", None))
        self.XLabel1.setText(_translate("DataBaseGUI", "X Axis: ", None))
        self.StartDateLabel.setText(_translate("DataBaseGUI", "Start date: ", None))
        self.YLabel1.setText(_translate("DataBaseGUI", "Y Axis: ", None))
        self.StartDateLabel_2.setText(_translate("DataBaseGUI", "End date: ", None))
        self.SizeLabel.setText(_translate("DataBaseGUI", "Marker Size: ", None))
        self.LegendLabel.setText(_translate("DataBaseGUI", "Legend: ", None))
        self.RefreshPlot1PushButton.setText(_translate("DataBaseGUI", "Refresh Plot 1 and Table 1", None))
        self.SaveMapPushButton.setText(_translate("DataBaseGUI", " Save Map to File: ", None))
        self.EndTimeLabel.setText(_translate("DataBaseGUI", "End time (min): ", None))
        self.StartTimeLabel.setText(_translate("DataBaseGUI", "Start time (min): ", None))
        self.YLabel2.setText(_translate("DataBaseGUI", "Y Axis: ", None))
        self.XLabel2.setText(_translate("DataBaseGUI", "X Axis: ", None))
        self.RefreshPlot2PushButton.setText(_translate("DataBaseGUI", "Refresh Plot 2 and Table 2 and update Table 1 values", None))
        self.SaveDataPushButton.setText(_translate("DataBaseGUI", " Save Data to File: ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab1), _translate("DataBaseGUI", "Scatter", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DataBaseGUI", "Histogram", None))
        self.WarningLabel1.setText(_translate("DataBaseGUI", "Displays 50 rows maximum.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab2), _translate("DataBaseGUI", "Table 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab3), _translate("DataBaseGUI", "Plot 2", None))
        self.WarningLabel2.setText(_translate("DataBaseGUI", "Displays 50 rows maximum.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab4), _translate("DataBaseGUI", "Table 2", None))

