# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FitBrowserGUIdesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FitBrowserGUI(object):
    def setupUi(self, FitBrowserGUI):
        FitBrowserGUI.setObjectName(_fromUtf8("FitBrowserGUI"))
        FitBrowserGUI.resize(2225, 1296)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FitBrowserGUI.sizePolicy().hasHeightForWidth())
        FitBrowserGUI.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(FitBrowserGUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.ControlsPanel = QtGui.QVBoxLayout(self.layoutWidget)
        self.ControlsPanel.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.ControlsPanel.setObjectName(_fromUtf8("ControlsPanel"))
        self.FilePathWidget = QtGui.QLineEdit(self.layoutWidget)
        self.FilePathWidget.setObjectName(_fromUtf8("FilePathWidget"))
        self.ControlsPanel.addWidget(self.FilePathWidget)
        self.NewFilePushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewFilePushButton.sizePolicy().hasHeightForWidth())
        self.NewFilePushButton.setSizePolicy(sizePolicy)
        self.NewFilePushButton.setObjectName(_fromUtf8("NewFilePushButton"))
        self.ControlsPanel.addWidget(self.NewFilePushButton)
        self.line_6 = QtGui.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.ControlsPanel.addWidget(self.line_6)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.FileContentsTableWidget = QtGui.QTableWidget(self.layoutWidget)
        self.FileContentsTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.FileContentsTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.FileContentsTableWidget.setObjectName(_fromUtf8("FileContentsTableWidget"))
        self.FileContentsTableWidget.setColumnCount(0)
        self.FileContentsTableWidget.setRowCount(0)
        self.gridLayout_3.addWidget(self.FileContentsTableWidget, 1, 0, 1, 1)
        self.MessageTypesLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MessageTypesLabel.sizePolicy().hasHeightForWidth())
        self.MessageTypesLabel.setSizePolicy(sizePolicy)
        self.MessageTypesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MessageTypesLabel.setObjectName(_fromUtf8("MessageTypesLabel"))
        self.gridLayout_3.addWidget(self.MessageTypesLabel, 0, 0, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_3)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.ControlsPanel.addWidget(self.line)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.MessageNumberBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.MessageNumberBox.setDecimals(0)
        self.MessageNumberBox.setMinimum(1.0)
        self.MessageNumberBox.setMaximum(10000.0)
        self.MessageNumberBox.setObjectName(_fromUtf8("MessageNumberBox"))
        self.gridLayout_2.addWidget(self.MessageNumberBox, 0, 1, 1, 1)
        self.MessageNumberLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MessageNumberLabel.sizePolicy().hasHeightForWidth())
        self.MessageNumberLabel.setSizePolicy(sizePolicy)
        self.MessageNumberLabel.setObjectName(_fromUtf8("MessageNumberLabel"))
        self.gridLayout_2.addWidget(self.MessageNumberLabel, 0, 0, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_2)
        self.line_4 = QtGui.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.ControlsPanel.addWidget(self.line_4)
        self.PrintPushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrintPushButton.sizePolicy().hasHeightForWidth())
        self.PrintPushButton.setSizePolicy(sizePolicy)
        self.PrintPushButton.setObjectName(_fromUtf8("PrintPushButton"))
        self.ControlsPanel.addWidget(self.PrintPushButton)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Tab1 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab1.sizePolicy().hasHeightForWidth())
        self.Tab1.setSizePolicy(sizePolicy)
        self.Tab1.setObjectName(_fromUtf8("Tab1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Tab1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.Plot1WidgetContainer = QtGui.QVBoxLayout()
        self.Plot1WidgetContainer.setObjectName(_fromUtf8("Plot1WidgetContainer"))
        self.verticalLayout_3.addLayout(self.Plot1WidgetContainer)
        self.tabWidget.addTab(self.Tab1, _fromUtf8(""))
        self.Tab2 = QtGui.QWidget()
        self.Tab2.setObjectName(_fromUtf8("Tab2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Tab2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Table1Widget = QtGui.QTableWidget(self.Tab2)
        self.Table1Widget.setObjectName(_fromUtf8("Table1Widget"))
        self.Table1Widget.setColumnCount(0)
        self.Table1Widget.setRowCount(0)
        self.verticalLayout.addWidget(self.Table1Widget)
        self.tabWidget.addTab(self.Tab2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.splitter)
        FitBrowserGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(FitBrowserGUI)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(FitBrowserGUI)

    def retranslateUi(self, FitBrowserGUI):
        FitBrowserGUI.setWindowTitle(_translate("FitBrowserGUI", "Fit Browser", None))
        self.NewFilePushButton.setText(_translate("FitBrowserGUI", "Select New File", None))
        self.MessageTypesLabel.setText(_translate("FitBrowserGUI", "File contents:", None))
        self.MessageNumberLabel.setText(_translate("FitBrowserGUI", "Message number: ", None))
        self.PrintPushButton.setText(_translate("FitBrowserGUI", "Print Message", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab1), _translate("FitBrowserGUI", "Plot 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab2), _translate("FitBrowserGUI", "Table 1", None))

